// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/middleware/fee/v1/genesis.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/ibc-go/modules/core/04-channel/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the fee middleware genesis state
type GenesisState struct {
	// A mapping of packets -> escrowed fees
	PacketsFeesMap []*GenesisState_PacketsFeesMapEntry `protobuf:"bytes,1,rep,name=packets_fees_map,json=packetsFeesMap,proto3" json:"packets_fees_map,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4f6c8d78b5dfbf, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetPacketsFeesMap() []*GenesisState_PacketsFeesMapEntry {
	if m != nil {
		return m.PacketsFeesMap
	}
	return nil
}

// An entry for the PacketsFees map
type GenesisState_PacketsFeesMapEntry struct {
	PacketId *types.PacketId `protobuf:"bytes,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	Fee      *Fee            `protobuf:"bytes,2,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (m *GenesisState_PacketsFeesMapEntry) Reset()         { *m = GenesisState_PacketsFeesMapEntry{} }
func (m *GenesisState_PacketsFeesMapEntry) String() string { return proto.CompactTextString(m) }
func (*GenesisState_PacketsFeesMapEntry) ProtoMessage()    {}
func (*GenesisState_PacketsFeesMapEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4f6c8d78b5dfbf, []int{0, 0}
}
func (m *GenesisState_PacketsFeesMapEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState_PacketsFeesMapEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState_PacketsFeesMapEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState_PacketsFeesMapEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState_PacketsFeesMapEntry.Merge(m, src)
}
func (m *GenesisState_PacketsFeesMapEntry) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState_PacketsFeesMapEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState_PacketsFeesMapEntry.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState_PacketsFeesMapEntry proto.InternalMessageInfo

func (m *GenesisState_PacketsFeesMapEntry) GetPacketId() *types.PacketId {
	if m != nil {
		return m.PacketId
	}
	return nil
}

func (m *GenesisState_PacketsFeesMapEntry) GetFee() *Fee {
	if m != nil {
		return m.Fee
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "ibc.applications.middleware.fee.v1.GenesisState")
	proto.RegisterType((*GenesisState_PacketsFeesMapEntry)(nil), "ibc.applications.middleware.fee.v1.GenesisState.PacketsFeesMapEntry")
}

func init() {
	proto.RegisterFile("ibc/applications/middleware/fee/v1/genesis.proto", fileDescriptor_6a4f6c8d78b5dfbf)
}

var fileDescriptor_6a4f6c8d78b5dfbf = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0x97, 0x0d, 0xfe, 0xfc, 0xed, 0x44, 0xa4, 0x7a, 0x18, 0x03, 0xcb, 0xdc, 0xc5, 0x1d,
	0x5c, 0xe2, 0xea, 0x69, 0x1e, 0x45, 0x27, 0x82, 0x82, 0xcc, 0x9b, 0x97, 0x91, 0xa6, 0x6f, 0xbb,
	0x60, 0x9b, 0x84, 0x26, 0x9b, 0xec, 0x3b, 0x28, 0xf8, 0xb1, 0x3c, 0xee, 0xe8, 0x51, 0xb6, 0x2f,
	0x22, 0x69, 0x26, 0x4e, 0x10, 0xdc, 0xed, 0xa1, 0xfd, 0x3d, 0xcf, 0xfb, 0xbc, 0x79, 0xbd, 0x13,
	0x1e, 0x31, 0x42, 0x95, 0xca, 0x38, 0xa3, 0x86, 0x4b, 0xa1, 0x49, 0xce, 0xe3, 0x38, 0x83, 0x27,
	0x5a, 0x00, 0x49, 0x00, 0xc8, 0xb4, 0x47, 0x52, 0x10, 0xa0, 0xb9, 0xc6, 0xaa, 0x90, 0x46, 0xfa,
	0x6d, 0x1e, 0x31, 0xbc, 0xee, 0xc0, 0xdf, 0x0e, 0x9c, 0x00, 0xe0, 0x69, 0xaf, 0xb9, 0x9f, 0xca,
	0x54, 0x96, 0x38, 0xb1, 0xca, 0x39, 0x9b, 0xc7, 0x1b, 0xcc, 0xb2, 0x01, 0x8e, 0x3e, 0xb4, 0x34,
	0x93, 0x05, 0x10, 0x36, 0xa6, 0x42, 0x40, 0x66, 0x7f, 0xaf, 0xa4, 0x43, 0xda, 0x2f, 0x55, 0x6f,
	0xfb, 0xca, 0x95, 0xbb, 0x37, 0xd4, 0x80, 0x2f, 0xbc, 0x5d, 0x45, 0xd9, 0x23, 0x18, 0x3d, 0x4a,
	0x00, 0xf4, 0x28, 0xa7, 0xaa, 0x81, 0x5a, 0xb5, 0x4e, 0x3d, 0xbc, 0xc0, 0x7f, 0xd7, 0xc6, 0xeb,
	0x59, 0xf8, 0xce, 0x05, 0x0d, 0x00, 0xf4, 0x2d, 0x55, 0x97, 0xc2, 0x14, 0xb3, 0xe1, 0x8e, 0xfa,
	0xf1, 0xb1, 0xf9, 0x8c, 0xbc, 0xbd, 0x5f, 0x38, 0xff, 0xcc, 0xdb, 0x72, 0xe4, 0x88, 0xc7, 0x0d,
	0xd4, 0x42, 0x9d, 0x7a, 0x78, 0x50, 0x16, 0xb0, 0xfb, 0xe0, 0xaf, 0x25, 0xa6, 0xbd, 0xd5, 0x90,
	0xeb, 0x78, 0xf8, 0x5f, 0xad, 0x94, 0xdf, 0xf7, 0x6a, 0x09, 0x40, 0xa3, 0x5a, 0xba, 0x8e, 0x36,
	0xa9, 0x3d, 0x00, 0x18, 0x5a, 0xcf, 0xf9, 0xcd, 0xdb, 0x22, 0x40, 0xf3, 0x45, 0x80, 0x3e, 0x16,
	0x01, 0x7a, 0x5d, 0x06, 0x95, 0xf9, 0x32, 0xa8, 0xbc, 0x2f, 0x83, 0xca, 0x43, 0x98, 0x72, 0x33,
	0x9e, 0x44, 0x98, 0xc9, 0x9c, 0x30, 0xa9, 0x73, 0xa9, 0x09, 0x8f, 0x58, 0x37, 0x95, 0x24, 0x97,
	0xf1, 0x24, 0x03, 0x6d, 0xef, 0xa2, 0x49, 0xd8, 0xef, 0xda, 0x3b, 0x98, 0x99, 0x02, 0x1d, 0xfd,
	0x2b, 0x1f, 0xf9, 0xf4, 0x33, 0x00, 0x00, 0xff, 0xff, 0x88, 0x29, 0xef, 0x17, 0x23, 0x02, 0x00,
	0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PacketsFeesMap) > 0 {
		for iNdEx := len(m.PacketsFeesMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PacketsFeesMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState_PacketsFeesMapEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState_PacketsFeesMapEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState_PacketsFeesMapEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Fee != nil {
		{
			size, err := m.Fee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.PacketId != nil {
		{
			size, err := m.PacketId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PacketsFeesMap) > 0 {
		for _, e := range m.PacketsFeesMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *GenesisState_PacketsFeesMapEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PacketId != nil {
		l = m.PacketId.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Fee != nil {
		l = m.Fee.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PacketsFeesMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PacketsFeesMap = append(m.PacketsFeesMap, &GenesisState_PacketsFeesMapEntry{})
			if err := m.PacketsFeesMap[len(m.PacketsFeesMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState_PacketsFeesMapEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PacketsFeesMapEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PacketsFeesMapEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PacketId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PacketId == nil {
				m.PacketId = &types.PacketId{}
			}
			if err := m.PacketId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Fee == nil {
				m.Fee = &Fee{}
			}
			if err := m.Fee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
