version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directories:
      - "/"
      - "/modules/light-clients/08-wasm"
      - "/e2e"
      - "/simapp"
    schedule:
      interval: daily
    labels:
      - dependencies
