queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=automerge

pull_request_rules:
  - name: automerge to main with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=automerge
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
           {{ title }} (#{{ number }})
           {{ body }}
  - name: backport patches to v1.0.x capability branch
    conditions:
      - base=main
      - label=backport-capability-to-v1.0.x
    actions:
      backport:
        branches:
          - capability/release/v1.0.x
  - name: backport patches to v0.1.x callbacks ibc-go v7.3.x branch
    conditions:
      - base=main
      - label=backport-callbacks-to-v0.1.x+ibc-go-v7.3.x
    actions:
      backport:
        branches:
          - callbacks/release/v0.1.x+ibc-go-v7.3.x
  - name: backport patches to v0.2.x callbacks ibc-go v7.3.x branch
    conditions:
      - base=main
      - label=backport-callbacks-to-v0.2.x+ibc-go-v7.3.x
    actions:
      backport:
        branches:
          - callbacks/release/v0.2.x+ibc-go-v7.3.x
  - name: backport patches to v0.1.x wasm ibc-go v7.3.x & wasmvm 1.4.x branch
    conditions:
      - base=main
      - label=backport-wasm-to-v0.1.x+ibc-go-v7.3.x-wasmvm-v1.4.x
    actions:
      backport:
        branches:
          - 08-wasm/release/v0.1.x+ibc-go-v7.3.x-wasmvm-v1.4.x
  - name: backport patches to v0.1.x wasm ibc-go v8.0.x & wasmvm 1.4.x branch
    conditions:
      - base=main
      - label=backport-wasm-to-v0.1.x+ibc-go-v8.0.x-wasmvm-v1.4.x
    actions:
      backport:
        branches:
          - 08-wasm/release/v0.1.x+ibc-go-v8.0.x-wasmvm-v1.4.x
  - name: backport patches to v6.1.x branch
    conditions:
      - base=main
      - label=backport-to-v6.1.x
    actions:
      backport:
        branches:
          - release/v6.1.x
  - name: backport patches to v6.2.x branch
    conditions:
      - base=main
      - label=backport-to-v6.2.x
    actions:
      backport:
        branches:
          - release/v6.2.x
  - name: backport patches to v7.2.x branch
    conditions:
      - base=main
      - label=backport-to-v7.2.x
    actions:
      backport:
        branches:
          - release/v7.2.x
  - name: backport patches to v7.3.x branch
    conditions:
      - base=main
      - label=backport-to-v7.3.x
    actions:
      backport:
        branches:
          - release/v7.3.x
  - name: backport patches to v8.0.x branch
    conditions:
      - base=main
      - label=backport-to-v8.0.x
    actions:
      backport:
        branches:
          - release/v8.0.x
