queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=automerge
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}
    merge_conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=automerge
    merge_method: squash

pull_request_rules:
  - name: backport patches to v7.10.x branch
    conditions:
      - base=main
      - label=backport-to-v7.10.x
    actions:
      backport:
        branches:
          - release/v7.10.x
  - name: backport patches to v8.8.x branch
    conditions:
      - base=main
      - label=backport-to-v8.8.x
    actions:
      backport:
        branches:
          - release/v8.8.x
  - name: backport patches to v10.4.x branch
    conditions:
      - base=main
      - label=backport-to-v10.4.x
    actions:
      backport:
        branches:
          - release/v10.4.x
  - name: automerge to main with label automerge and branch protection passing
    conditions: []
    actions:
      queue:
