version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - mirror
    - copyloopvar
    - iface
    - importas
    - intrange
    - nakedret
    - nilnesserr
    - nilnil
    - nonamedreturns
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - testifylint
    - testpackage
    - usestdlibvars
    - usetesting
    - wastedassign
  settings:
    gosec:
      excludes:
        - G107 # Url provided to HTTP request as taint input
        - G115 # Potential integer overflow when converting between integer types
        - G404 # Insecure random number source (rand)
      confidence: low
    nakedret:
      max-func-lines: 0
    revive:
      enable-all-rules: true
      # See the rule descriptions here: https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md
      rules:
        # Rules with configuration
        - name: receiver-naming
          disabled: false
          arguments:
            - max-length: 4
        - name: unhandled-error
          disabled: false
          arguments: # Disable for these ones only
            - fmt.Printf
            - fmt.Print
            - fmt.Println
        # Disabled rules
        # TODO: Some of these are kinda code smelly, should reconsider some of them
        - name: add-constant
          disabled: true
        - name: argument-limit
          disabled: true
        - name: banned-characters
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: confusing-results
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: deep-exit
          disabled: true
        - name: function-length
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'SA1019:' # TODO: This should really be removed!
      - path: _test\.go
        linters:
          - prealloc
      - path: e2e/*
        linters:
          - prealloc
          - testpackage
      - path: testing/*
        linters:
          - prealloc
    paths:
      - third_party$
      - builtin$
      - examples$
      - testing/mock/*
issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - prefix(cosmossdk.io)
        - prefix(github.com/cosmos/cosmos-sdk)
        - prefix(github.com/cometbft/cometbft)
        - prefix(github.com/cosmos/ibc-go)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
