coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
ignore:
- "**/*.pb.go"
- "**/*.pb.gw.go"
- "docs"
- "simapp"
- "testing"
- "modules/light-clients/08-wasm/testing"
- "scripts"
- "contrib"
- "cmd"
