codecov:
  notify:
    wait_for_ci: true
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 5
        base: auto
        informational: true
        flags:
          - ibc-go
          - 08-wasm
comment:
  require_changes: "coverage_drop OR uncovered_patch" # Only comment when coverage drops or there is uncovered code in the commit
ignore:
- "**/*.pb.go"
- "**/*.pb.gw.go"
- "docs"
- "simapp"
- "**/testing/**"
- "testing"
- "scripts"
- "contrib"
- "cmd"
- "e2e"
