// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/ccv/v1/ccv.proto

package types

import (
	fmt "fmt"
	types1 "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/tendermint/tendermint/abci/types"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Status defines if the ccv channel is in one of the following states:
// UNINITIALIZED, INITIALIZING, VALIDATING, INVALID
type Status int32

const (
	// Default State
	UNINITIALIZED Status = 0
	// channel is in handshake process
	INITIALIZING Status = 1
	// channel is open and validating
	VALIDATING Status = 2
	// channel is invalid and can no longer process packets
	INVALID Status = 3
)

var Status_name = map[int32]string{
	0: "STATUS_UNINITIALIZED_UNSPECIFIED",
	1: "STATUS_INITIALIZING",
	2: "STATUS_VALIDATING",
	3: "STATUS_INVALID",
}

var Status_value = map[string]int32{
	"STATUS_UNINITIALIZED_UNSPECIFIED": 0,
	"STATUS_INITIALIZING":              1,
	"STATUS_VALIDATING":                2,
	"STATUS_INVALID":                   3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e30f5b03285d5746, []int{0}
}

// This packet is sent from parent chain to baby chain if the validator set for baby chain
// changes (due to new bonding/unbonding messages or slashing events)
// The acknowledgement from baby chain will be sent asynchronously once unbonding period is over,
// and this will function as `UnbondingOver` message for this packet.
type ValidatorSetChangePacketData struct {
	ValidatorUpdates []types.ValidatorUpdate `protobuf:"bytes,1,rep,name=validator_updates,json=validatorUpdates,proto3" json:"validator_updates" yaml:"validator_updates"`
}

func (m *ValidatorSetChangePacketData) Reset()         { *m = ValidatorSetChangePacketData{} }
func (m *ValidatorSetChangePacketData) String() string { return proto.CompactTextString(m) }
func (*ValidatorSetChangePacketData) ProtoMessage()    {}
func (*ValidatorSetChangePacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30f5b03285d5746, []int{0}
}
func (m *ValidatorSetChangePacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorSetChangePacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorSetChangePacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorSetChangePacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorSetChangePacketData.Merge(m, src)
}
func (m *ValidatorSetChangePacketData) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorSetChangePacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorSetChangePacketData.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorSetChangePacketData proto.InternalMessageInfo

func (m *ValidatorSetChangePacketData) GetValidatorUpdates() []types.ValidatorUpdate {
	if m != nil {
		return m.ValidatorUpdates
	}
	return nil
}

// CreateChildChainProposal is a governance proposal on the parent chain to spawn a new child chain.
// If it passes, then all validators on the parent chain are expected to validate the child chain at spawn time
// or get slashed. It is recommended that spawn time occurs after the proposal end time.
type CreateChildChainProposal struct {
	ChainId     string      `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty" yaml:"chain_id"`
	ClientState *types1.Any `protobuf:"bytes,2,opt,name=client_state,json=clientState,proto3" json:"client_state,omitempty" yaml:"client_state"`
	// genesis hash with no staking information included.
	GenesisHash []byte `protobuf:"bytes,3,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty" yaml:"genesis_hash"`
	// spawn time is the time on the parent chain at which the child chain genesis is finalized and all validators
	// will be responsible for starting their child chain validator node.
	SpawnTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=spawn_time,json=spawnTime,proto3" json:"spawn_time,omitempty" yaml:"spawn_time"`
}

func (m *CreateChildChainProposal) Reset()         { *m = CreateChildChainProposal{} }
func (m *CreateChildChainProposal) String() string { return proto.CompactTextString(m) }
func (*CreateChildChainProposal) ProtoMessage()    {}
func (*CreateChildChainProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30f5b03285d5746, []int{1}
}
func (m *CreateChildChainProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateChildChainProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateChildChainProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateChildChainProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChildChainProposal.Merge(m, src)
}
func (m *CreateChildChainProposal) XXX_Size() int {
	return m.Size()
}
func (m *CreateChildChainProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChildChainProposal.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChildChainProposal proto.InternalMessageInfo

func (m *CreateChildChainProposal) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *CreateChildChainProposal) GetClientState() *types1.Any {
	if m != nil {
		return m.ClientState
	}
	return nil
}

func (m *CreateChildChainProposal) GetGenesisHash() []byte {
	if m != nil {
		return m.GenesisHash
	}
	return nil
}

func (m *CreateChildChainProposal) GetSpawnTime() *timestamppb.Timestamp {
	if m != nil {
		return m.SpawnTime
	}
	return nil
}

func init() {
	proto.RegisterEnum("ibc.applications.ccv.v1.Status", Status_name, Status_value)
	proto.RegisterType((*ValidatorSetChangePacketData)(nil), "ibc.applications.ccv.v1.ValidatorSetChangePacketData")
	proto.RegisterType((*CreateChildChainProposal)(nil), "ibc.applications.ccv.v1.CreateChildChainProposal")
}

func init() { proto.RegisterFile("ibc/applications/ccv/v1/ccv.proto", fileDescriptor_e30f5b03285d5746) }

var fileDescriptor_e30f5b03285d5746 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0xcb, 0x6a, 0xdb, 0x4a,
	0x18, 0xb6, 0x92, 0x90, 0x9c, 0x8c, 0x7d, 0x72, 0x6c, 0x25, 0x87, 0xa8, 0x6a, 0x91, 0x54, 0x41,
	0xc1, 0x2d, 0x54, 0x83, 0xd3, 0x45, 0x21, 0x3b, 0x5f, 0xd2, 0x56, 0x10, 0x8c, 0xf1, 0x25, 0x8b,
	0x6c, 0xc4, 0x68, 0x34, 0x95, 0x86, 0x4a, 0x1a, 0xe1, 0x19, 0xbb, 0xf8, 0x0d, 0x8a, 0x37, 0xed,
	0x0b, 0x78, 0xd5, 0x5d, 0x1f, 0xa1, 0x4f, 0x90, 0x65, 0x96, 0x5d, 0x99, 0x92, 0xbc, 0x81, 0x9f,
	0xa0, 0xe8, 0xe2, 0xc4, 0x69, 0x56, 0xd2, 0xf7, 0x7f, 0x17, 0x3e, 0xfe, 0xe1, 0x07, 0xcf, 0xa9,
	0x8b, 0x21, 0x4a, 0x92, 0x90, 0x62, 0x24, 0x28, 0x8b, 0x39, 0xc4, 0x78, 0x0a, 0xa7, 0x8d, 0xf4,
	0x63, 0x25, 0x63, 0x26, 0x98, 0x7c, 0x4c, 0x5d, 0x6c, 0x6d, 0x4a, 0xac, 0x94, 0x9b, 0x36, 0xd4,
	0x23, 0x9f, 0xf9, 0x2c, 0xd3, 0xc0, 0xf4, 0x2f, 0x97, 0xab, 0x1a, 0x66, 0x3c, 0x62, 0x1c, 0xba,
	0x88, 0x13, 0x38, 0x6d, 0xb8, 0x44, 0xa0, 0x06, 0xc4, 0x8c, 0xc6, 0x05, 0xff, 0x54, 0x90, 0xd8,
	0x23, 0xe3, 0x88, 0xc6, 0x02, 0x22, 0x17, 0x53, 0x28, 0x66, 0x09, 0xe1, 0x05, 0xf9, 0xc4, 0x67,
	0xcc, 0x0f, 0x09, 0xcc, 0x90, 0x3b, 0xf9, 0x08, 0x51, 0x3c, 0x2b, 0x28, 0xfd, 0x6f, 0x4a, 0xd0,
	0x88, 0x70, 0x81, 0xa2, 0x24, 0x17, 0x98, 0x5f, 0x25, 0xf0, 0xec, 0x02, 0x85, 0xd4, 0x43, 0x82,
	0x8d, 0x07, 0x44, 0xb4, 0x03, 0x14, 0xfb, 0xa4, 0x87, 0xf0, 0x27, 0x22, 0x3a, 0x48, 0x20, 0x99,
	0x81, 0xda, 0x74, 0xcd, 0x3b, 0x93, 0xc4, 0x43, 0x82, 0x70, 0x45, 0x32, 0xb6, 0xeb, 0xe5, 0x13,
	0xc3, 0xba, 0x6f, 0x65, 0xa5, 0xad, 0xac, 0xbb, 0xa4, 0x51, 0x26, 0x6c, 0x19, 0x57, 0x4b, 0xbd,
	0xb4, 0x5a, 0xea, 0xca, 0x0c, 0x45, 0xe1, 0xa9, 0xf9, 0x28, 0xc8, 0xec, 0x57, 0xa7, 0x0f, 0x2d,
	0xdc, 0xfc, 0xb1, 0x05, 0x94, 0xf6, 0x98, 0x20, 0x41, 0xda, 0x01, 0x0d, 0xbd, 0x76, 0x80, 0x68,
	0xdc, 0x1b, 0xb3, 0x84, 0x71, 0x14, 0xca, 0x16, 0xf8, 0x07, 0xa7, 0x03, 0x87, 0x7a, 0x8a, 0x64,
	0x48, 0xf5, 0xfd, 0xd6, 0xe1, 0x6a, 0xa9, 0xff, 0x97, 0xc7, 0xaf, 0x19, 0xb3, 0xbf, 0x97, 0xfd,
	0xda, 0x9e, 0xdc, 0x03, 0x15, 0x1c, 0x52, 0x12, 0x0b, 0x87, 0x0b, 0x24, 0x88, 0xb2, 0x65, 0x48,
	0xf5, 0xf2, 0xc9, 0x91, 0x95, 0xaf, 0xc5, 0x5a, 0xaf, 0xc5, 0x6a, 0xc6, 0xb3, 0xd6, 0xf1, 0x6a,
	0xa9, 0x1f, 0x16, 0x49, 0x1b, 0x1e, 0xb3, 0x5f, 0xce, 0xe1, 0x20, 0x45, 0xf2, 0x29, 0xa8, 0xf8,
	0x24, 0x26, 0x9c, 0x72, 0x27, 0x40, 0x3c, 0x50, 0xb6, 0x0d, 0xa9, 0x5e, 0xd9, 0xf4, 0x6e, 0xb2,
	0x66, 0xbf, 0x5c, 0xc0, 0x0f, 0x88, 0x07, 0x72, 0x0f, 0x00, 0x9e, 0xa0, 0xcf, 0xb1, 0x93, 0xbe,
	0x82, 0xb2, 0x93, 0x75, 0x51, 0x1f, 0x75, 0x19, 0xae, 0x9f, 0xa8, 0xf5, 0xff, 0x6a, 0xa9, 0xd7,
	0xf2, 0xd4, 0x7b, 0x9f, 0xd9, 0xdf, 0xcf, 0x40, 0x2a, 0x7b, 0xf5, 0x53, 0x02, 0xbb, 0x69, 0xaf,
	0x09, 0x97, 0xdf, 0x02, 0x63, 0x30, 0x6c, 0x0e, 0x47, 0x03, 0x67, 0xd4, 0xb5, 0xbb, 0xf6, 0xd0,
	0x6e, 0x9e, 0xdb, 0x97, 0x67, 0x1d, 0x67, 0xd4, 0x1d, 0xf4, 0xce, 0xda, 0xf6, 0x3b, 0xfb, 0xac,
	0x53, 0x2d, 0xa9, 0xb5, 0xf9, 0xc2, 0xf8, 0xf7, 0x81, 0x40, 0x7e, 0x09, 0x0e, 0x0b, 0xe3, 0xdd,
	0xd4, 0xee, 0xbe, 0xaf, 0x4a, 0x6a, 0x75, 0xbe, 0x30, 0x2a, 0x9b, 0x33, 0xf9, 0x05, 0xa8, 0x15,
	0xd2, 0x8b, 0xe6, 0xb9, 0xdd, 0x69, 0x0e, 0x53, 0xe1, 0x96, 0x7a, 0x30, 0x5f, 0x18, 0xe0, 0x7e,
	0x22, 0xeb, 0xe0, 0xe0, 0x2e, 0x31, 0x1b, 0x57, 0xb7, 0xd5, 0xf2, 0x7c, 0x61, 0xec, 0x15, 0x50,
	0xdd, 0xf9, 0xf2, 0x5d, 0x2b, 0xb5, 0xec, 0xab, 0x1b, 0x4d, 0xba, 0xbe, 0xd1, 0xa4, 0xdf, 0x37,
	0x9a, 0xf4, 0xed, 0x56, 0x2b, 0x5d, 0xdf, 0x6a, 0xa5, 0x5f, 0xb7, 0x5a, 0xe9, 0x12, 0xfa, 0x54,
	0x04, 0x13, 0xd7, 0xc2, 0x2c, 0x82, 0xc5, 0x65, 0x50, 0x17, 0xbf, 0xf6, 0x19, 0x8c, 0x98, 0x37,
	0x09, 0x09, 0x4f, 0xaf, 0x2f, 0xbf, 0xba, 0xec, 0x10, 0xdc, 0xdd, 0x6c, 0x7b, 0x6f, 0xfe, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x0b, 0x66, 0x04, 0xef, 0x9a, 0x03, 0x00, 0x00,
}

func (m *ValidatorSetChangePacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorSetChangePacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorSetChangePacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorUpdates) > 0 {
		for iNdEx := len(m.ValidatorUpdates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorUpdates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCcv(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CreateChildChainProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateChildChainProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateChildChainProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SpawnTime != nil {
		{
			size, err := m.SpawnTime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCcv(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.GenesisHash) > 0 {
		i -= len(m.GenesisHash)
		copy(dAtA[i:], m.GenesisHash)
		i = encodeVarintCcv(dAtA, i, uint64(len(m.GenesisHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ClientState != nil {
		{
			size, err := m.ClientState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCcv(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintCcv(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCcv(dAtA []byte, offset int, v uint64) int {
	offset -= sovCcv(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValidatorSetChangePacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ValidatorUpdates) > 0 {
		for _, e := range m.ValidatorUpdates {
			l = e.Size()
			n += 1 + l + sovCcv(uint64(l))
		}
	}
	return n
}

func (m *CreateChildChainProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovCcv(uint64(l))
	}
	if m.ClientState != nil {
		l = m.ClientState.Size()
		n += 1 + l + sovCcv(uint64(l))
	}
	l = len(m.GenesisHash)
	if l > 0 {
		n += 1 + l + sovCcv(uint64(l))
	}
	if m.SpawnTime != nil {
		l = m.SpawnTime.Size()
		n += 1 + l + sovCcv(uint64(l))
	}
	return n
}

func sovCcv(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCcv(x uint64) (n int) {
	return sovCcv(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ValidatorSetChangePacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCcv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorSetChangePacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorSetChangePacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorUpdates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCcv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCcv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCcv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorUpdates = append(m.ValidatorUpdates, types.ValidatorUpdate{})
			if err := m.ValidatorUpdates[len(m.ValidatorUpdates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCcv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCcv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateChildChainProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCcv
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateChildChainProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateChildChainProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCcv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCcv
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCcv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCcv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCcv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCcv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ClientState == nil {
				m.ClientState = &types1.Any{}
			}
			if err := m.ClientState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCcv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCcv
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCcv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenesisHash = append(m.GenesisHash[:0], dAtA[iNdEx:postIndex]...)
			if m.GenesisHash == nil {
				m.GenesisHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpawnTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCcv
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCcv
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCcv
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SpawnTime == nil {
				m.SpawnTime = &timestamppb.Timestamp{}
			}
			if err := m.SpawnTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCcv(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCcv
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCcv(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCcv
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCcv
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCcv
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCcv
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCcv
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCcv
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCcv        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCcv          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCcv = fmt.Errorf("proto: unexpected end of group")
)
