name: Auto Tidy for Dependabot PRs

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git ref or branch to tidy'
        required: true
        default: 'main'
  
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tidy:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Determine ref to checkout
        id: branch_name
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # Use the provided input or fall back to default branch
            if [ -n "${{ github.event.inputs.branch }}" ]; then
              echo "ref=${{ github.event.inputs.branch }}" >>"$GITHUB_OUTPUT"
            else
              echo "ref=${{ github.ref }}" >>"$GITHUB_OUTPUT"
            fi
          else
            # On a Dependabot PR, use the PR head ref
            echo "ref=${{ github.event.pull_request.head.ref }}" >>"$GITHUB_OUTPUT"
            echo "repo=${{ github.event.pull_request.head.repo.full_name }}" >>"$GITHUB_OUTPUT"
          fi

      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch_name.outputs.ref }}
          repository: ${{ steps.branch_name.outputs.repo || github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run make tidy-all
        run: make tidy-all

      - name: Commit & push tidy changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: run make tidy-all"
            git push origin HEAD:${{ steps.branch_name.outputs.ref }}
          else
            echo "No changes after make tidy-all"
          fi
