name: Dependabot Tidy

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tidy:
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.DEPENDABOT_PUSH_PAT }}
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Run make tidy-all
        run: make tidy-all

      - name: Commit changes if any
        id: commit
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: run make tidy-all"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes after make tidy-all"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Push changes if any
        if: ${{ steps.commit.outputs.changed == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEPENDABOT_PUSH_PAT }}
          branch: ${{ github.event.pull_request.head.ref }}
          force_with_lease: true
