name: Check Markdown links
on:
  pull_request:
    paths:
      - "**.md"
      - "!.github/**"
jobs:
  markdown-link-check:
    depot-ubuntu-22.04-4
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.github/workflows/link-check-config.json'
