# SPDX-License-Identifier: Apache-2.0

name: Buf-Push
# Protobuf runs buf (https://buf.build/) push updated proto files to https://buf.build/cosmos/ibc
# This workflow is only run when a .proto file has been changed
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "proto/**"
    tags:
      - 'v*.*.*'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  push:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: bufbuild/buf-action@85aebf73123b5c15fd5528aaecbf9129cddf7fa7 # v1.6.0
        with:
          token: ${{ secrets.BUF_TOKEN }}
          setup_only: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input: "proto"
          push: true
          lint: false
          format: false
          breaking: false
